remote_theme: pmarsceill/just-the-docs
color_scheme: dark
markdown: GFM
title: meteor-lists
url: "https://anticope.github.io"
plugins:
  - jekyll-sitemap

gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap
