theme: jekyll-theme-hacker
markdown: GFM
title: meteor-lists
url: "https://anticope.github.io"
plugins:
  - jekyll-sitemap

gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap
  
defaults:
 - scope:
    path: *.md
