remote_theme: "dracula/gh-pages"
markdown: GFM
title: meteor-lists
url: "https://anticope.github.io"
show_downloads: false
show_header: true
plugins:
  - jekyll-sitemap

gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap
