remote_theme: pmarsceill/just-the-docs
color_scheme: dark
markdown: GFM
logo: "https://github.com/AntiCope/meteor-lists/blob/master/res/icon.png?raw=true"
title: meteor-lists
url: "https://anticope.github.io"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/AntiCope/meteor-lists"
gh_edit_branch: "master"
gh_edit_view_mode: "tree"


plugins:
  - jekyll-sitemap

gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap
