name: Update Table of Contents

concurrency:
  group: "main"
  cancel-in-progress: false

on:
  push:
    paths:
      - 'pages/*.md'
      - 'pages/*/*.md'
      - '.github/workflows/toc.yml'
  workflow_run:
    workflows: ["Generate UntestedAddons.md"]
    types:
      - completed
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate TOC
        uses: technote-space/toc-generator@v4
        with:
          FOLDING: true
          TARGET_PATHS: 'pages/*.md, pages/*/*.md'
          COMMIT_NAME: "AntiCope"
          COMMIT_EMAIL: "88768753+AntiCope@users.noreply.github.com"
